### ISSUE TITLE
it crashes on its own

### ISSUE THREAD

**Issue by KibaTheBarbarian** [AmarokIce/WithWolfhouse#1]
booted my pack notice it crashed and I booted it on its own and still crash [crash log](https://pastebin.com/aupfQEe1)

**Comment by AmarokIce** [comment]
Should ASJCore
https://www.curseforge.com/minecraft/mc-mods/asjcore

**Comment by KibaTheBarbarian** [comment]
thank you for the information it's just that the new curse page sucks showing the the info
